name: 'Treeware'
description: 'Generates a categorized changelog and releases your prod or beta.'
author: 'tronku'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token to access your repo'
    required: true

  prod_branch:
    description: 'Production branch of the repo'
    required: true
    default: 'development'
    
  drafter_path: 
    description: 'Path to the drafter file'
    required: true

  should_release:
    description: 'Should release a new version?'
    required: false
    default: 'false'
  
  version_name:
    description: 'Version name of the upcoming release'
    required: false

  is_beta:
    description: 'Is this a beta release?'
    required: false
    default: 'false'

  beta_branch:
    description: 'Beta branch of the repo for release'
    required: false

  assets:
    description: 'Path to the assets, separated by comma'
    required: false
    default: ''

  target_commitish:
    description: 'Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA.'
    default: ''
    required: false

  prerelease:
    description: 'Is this a prerelease?'
    default: 'false'
    required: false
  
  is_draft:
    description: 'Is this just a draft of the release?'
    default: 'false'
    required: false
  
  extra_release_note:
    description: 'Extra note to add in the GitHub release notes'
    default: ''
    required: false

outputs:
  changelogs:
    description: 'Categorized changelogs based on labels'
  
  upload_url:
    description: 'The assets upload URL to the GitHub release'

  release_url:
    description: 'The URL to the GitHub release'  


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.prod_branch }}
    - ${{ inputs.drafter_path }}
    - ${{ inputs.should_release }}
    - ${{ inputs.is_beta }}
    - ${{ inputs.version_name }}
    - ${{ inputs.assets }}
    - ${{ inputs.beta_branch }}
    - ${{ inputs.target_commitish }} 
    - ${{ inputs.prerelease }}
    - ${{ inputs.is_draft }}
    - ${{ inputs.extra_release_note }}